# DATA TYPES AND STRUCTURE QUESTIONS

#Theory Questions :

**Q1. What are data structures, and why are they important ?**

**Explanation:**
 Data structures are ways of organizing and storing data so it can be accessed and modified efficiently.

Examples: lists, tuples, sets, dictionaries.

Importance: They make searching, sorting, and manipulating data faster and more efficient, which improves program performance.

**Q2. Explain the difference between mutable and immutable data types with examples ?**

**Explanation** :
> Mutable: Can be changed after creation.
>> Example:

In [ ]:
my_list = [1, 2, 3]
my_list[0] = 10  # list is mutable
print(my_list)

[10, 2, 3]

Immutable: Cannot be changed after creation.
>Example:

In [ ]:
my_string = "hello"
# my_string[0] = "H" is not allowed because if we do that this will generate error
print(my_string)

hello

**Q3. What are the main differences between lists and tuples in Python ?**

** Explanation :**
 1. Syntax :

  * List: Written with square brackets []
  * my_list = [1, 2, 3]

  * Tuple: Written with parentheses ()
  * my_tuple = (1, 2, 3)

2. Mutability :

 * List: Mutable -> You can add, remove, or change elements.
 * my_list[0] = 10   # It will give output as 10 at index 0

  * Tuple: Immutable -> Once created, it cannot be changed.

  * my_tuple[0] = 10   # error

3. Performance

  * List: Slightly slower (because it supports modifications).

  * Tuple: Faster (because it's fixed and cannot change).

4. Use Cases

  * List: Used when you need a dynamic collection (adding/removing items).

  * Tuple: Used when you need fixed data (like days of the week, coordinates).

5. Methods Available

  * List: Has many methods like append(), remove(), sort(), etc.

  * Tuple: Has only two methods -> count() and index().

**Q4. Describe how dictionaries store data.**

**Explanation :** Dictionaries store data in key-value pairs using a hash table internally. Example:

    student = {"name": "Alice", "age": 20}

**Q5. Why might you use a set instead of a list in Python**

**Explanation :**
* To remove duplicates automatically.

* To perform set operations like union, intersection.

**Q6. What is a string in Python, and how is it different from a list ?**

**Explanation:** A string is a sequence of characters enclosed in quotes.

 Example: "hello".

**Difference**:

String is immutable, list is mutable.

String stores only characters, list can store mixed data.

**Q7. How to tuples ensure data integrity in Python ?**

**Explanation :** Because tuples are immutable, once created, their values cannot be modified. This prevents accidental changes.

**Q8. What is a hash table, and how does it relate to dictonaries in Python ?**

**Explanation :**

Hash table:A hash table is a special data structure that stores data in the form of key value pairs and allows very fast access to values using keys.

Python’s dictionary is implemented using a hash table.
  
**Q9. Can lists contain different data types in Python?**

**Explanation :**

Yes. Example:

    mixed = [1, "hello", 3.14, True]

**Q10. Explain why strings are immutable in python.**

**Explanation :**

* For security, efficiency, and hashing (so they can be dictionary keys).

* Any modification creates a new string.

**Q11. What advantages do dictionaries after over lists for certain tasks?**

**Explanation :**

* Fast lookups by key (O(1) average time).

* More meaningful data storage (key-value pairs).

**Q12. Describe a scenario where using a tuple would be preferable over a list.**

**Explanation :**

When storing constant data like days of the week:

    Days = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")

**Q13. How do sets handle duplicate values in Python?**

**Explanation :**

Sets automatically remove duplicates.

In [ ]:
s = {1, 2, 2, 3}
print(s)  # {1, 2, 3)

{1, 2, 3}

**Q14. How does the “in” keyword work differently for lists and dictionaries?**

**Explanation :**

* In lists: checks if value exists.

* In dictionaries: checks if key exists.

**Q15. . Can you modify the elements of a tuple? Explain why or why not.**

**Explanation :**
No, tuples are immutable. Once created, elements cannot be changed.

**Q16. 16. What is a nested dictionary, and give an example of its use case.**

A dictionary inside another dictionary.

Example:

    students = {
      "student1": {"name": "Alice", "age": 20},
      "student2": {"name": "Bob", "age": 22}
    }

**Q17. Describe the time complexity of accessing elements in a dictionary.**

**Explanation :**

* Average: O(1) (constant time).

* Worst case (rare): O(n).

**Q18. 18. In what situations are lists preferred over dictionaries?

* When order matters.

* When you only need sequential data without key-value pairs.**

**Q19. Why are dictonaries considered unordered, and how does that affect data retrieval?**

**Explanation :**

Before Python 3.7, dictionaries did not maintain insertion order.

Retrieval is based on keys, not position.

**Q20. Explain the difference between a list and a dictionary in terms of data retrieval.**

**Explanation :**
List: Retrieve by index. Example: my_list[0].

Dictionary: Retrieve by key. Example: my_dict["name"].


#Practical Questions :

**Q1. Write a code to create a string with your name and print it.**

In [ ]:
name = "LEGEND"
print(name)

LEGEND

**Q2. Write a code to find the length of the string "Hello World".**

In [ ]:
print(len("Hello World"))

11

**Q3. Write a code to slice the first 3 characters from the string "Python Programming**

In [ ]:
print("Python Programming"[:3])

Pyt

**Q4. Write a code to convert the string "hello" to uppercase**

In [ ]:
print("hello".upper())

HELLO

**Q5. Write a code to replace the word "apple" with "orange" in the string "I like apple".**

In [ ]:
print("I like apple".replace("apple", "orange"))

I like orange

**Q6. Write a code to create a list with numbers 1 to 5 and print it.**

In [ ]:
Num = [1,2,3,4,5]
print(Num)

[1, 2, 3, 4, 5]

**Q7. Write a code to append the number 10 to the list [1,2,3,4].**

In [ ]:
lst = [1,2,3,4]
lst.append(10)
print(lst)

[1, 2, 3, 4, 10]

**Q8. Write a code to remove the number 3 from the list [1,2,3,4,5].**

In [ ]:
num = [1,2,3,4,5]
num.remove(3)
print(num)

[1, 2, 4, 5]

**Q9. Write a code to access the second element in the list ['a', 'b', 'c', 'd'].**

In [ ]:
lst = ['a','b','c','d']
print(lst[1])

b

**Q10. Write a code to reverse the list [10,20,30,40,50].**

In [ ]:
lst = [10,20,30,40,50]
lst.reverse()
print(lst)

[50, 40, 30, 20, 10]

**Q11. Write a code to create a tuple with the elements 100,200,300 and print it.**

In [ ]:
t = (100,200,300)
print(t)

(100, 200, 300)

**Q12. Write a code to access the second-to-last element of the tuple ('red','green','blue','yellow').**

In [ ]:
access_second = ('red','green','blue','yellow')
print(access_second[-2])

blue

**Q13. Write a code to find the minimum number in the tuple (10,20,5,15).**

In [ ]:
min_num = (10,20,5,15)
print(min(min_num))

5

**Q14. Write a code to find the index of the element "cat" in the tuple ('dog','cat','rabbit').**

In [ ]:
alpha = ('dog','cat','rabbit')
print(alpha.index("cat"))

1

**Q15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.**

In [ ]:
fruits = ("apple","banana","mango")
print("kiwi" in fruits)

False

**Q16. Write a code to create a set with the elements 'a', 'b', 'c' and print it.**

In [ ]:
s = {'a','b','c'}
print(s)

{'a', 'b', 'c'}

**Q17. Write a code to clear all elements from the set {1,2,3,4,5}.**

In [ ]:
s = {1,2,3,4,5}
s.clear()
print(s)

set()

**Q18. Write a code to remove the element 4 from the set {1,2,3,4}.**

In [ ]:
s = {1,2,3,4}
s.remove(4)
print(s)

{1, 2, 3}

**Q19. Write a code to find the union of two sets {1,2,3} and {3,4,5}.**

In [ ]:
s1 = {1,2,3}
s2 = {3,4,5}
print(s1.union(s2))

{1, 2, 3, 4, 5}

**Q20. Write a code to find the intersection of two sets {1,2,3} and {2,3,4}.**

In [ ]:
s1={1,2,3}
s2={2,3,4}
print(s1.intersection(s2))

{2, 3}

**Q21. Write a code to create a dictionary with the keys "name", "age", and "city", and print it.**

In [ ]:
Data = {"name":"Mahesh", "age":20, "city":"Delhi"}
print(Data)

{'name': 'Mahesh', 'age': 20, 'city': 'Delhi'}

**Q22. Write a code to add a new key-value pair "country":"USA" to the dictionary {'name': 'John', 'age': 25}**

In [ ]:
new = {'name':'John','age':25}
new['country'] = 'USA'
print(new)

{'name': 'John', 'age': 25, 'country': 'USA'}

**Q23. Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice' , 'age': 30}.**

In [ ]:
data = {'name':'Alice','age':30}
print(data['name'])

Alice

**Q24. Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.**

In [ ]:
remove = {'name':'Bob','age':22,'city':'New York'}
remove.pop('age')
print(remove)

{'name': 'Bob', 'city': 'New York'}

**Q25. Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.**

In [ ]:
exists = {'name':'Alice','city':'Paris'}
print("city" in exists)

True

**Q26. Write a code to create a list, a tuple, and a dictionary, and print them all.**

In [ ]:
li_st = [1,2,3]
tup_le = (10,20,30)
dict_ionary = {"a":1,"b":2}
print(li_st, tup_le, dict_ionary)

[1, 2, 3] (10, 20, 30) {'a': 1, 'b': 2}

**Q27. Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result.(replaced)**

In [ ]:
import random
lst = random.sample(range(1,101),5)
lst.sort()
print(lst)

[12, 71, 82, 93, 100]

**Q28. Write a code to create a list with strings and print the element at the third index.**

In [ ]:
lst = ["apple","banana","strawberry","mango"]
print(lst[3])

mango

**Q29. Write a code to combine two dictionaries into one and print the result.**

In [ ]:
d1 = {"a":1,"b":2}
d2 = {"c":3,"d":4}
d1.update(d2)
print(d1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

**Q30. Write a code to convert a list of strings into a set.**

In [ ]:
lst = ["apple","banana","apple","mango"]
s = set(lst)
print(s)

{'banana', 'apple', 'mango'}